import numpy as np
import pandas as pd

TARGET_COLUMN="Result"
PIPELINE_NAME="NetworkSecurity"
ARTIFACT_DIR="Artifacts"
FILE_NAME="phishingData.csv"
TRAIN_FILE_NAME="train.csv"
TEST_FILE_NAME="test.csv"

DATA_INGESTION_DIR="data_ingestion"
DATA_INGESTION_COLLECTION_NAME="dataset"
DATA_INGESTION_INGESTED_DIR="ingested"
DATA_INGESTION_DATABASE_NAME="ML-NSProj"
DATA_INGESTION_FEATURE_STORE_DIR="feature_store"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO=0.2